name: CI

on: [push]
env:
  TEST_PATH: '/mnt/cache'
  TEST_PATH2: '/mnt/cache2'
  ALL_COVERAGE: 'qaz'
  REQUIRE_COVERAGE: '345'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        python test/env.py
        echo $IS_COVERAGE

    - name: Generate coverage report
      run: |
        pip install pytest-cov
        bash -c "echo ${TEST_PATH}"
        bash -c 'echo ${TEST_PATH2}'

  Op-Test-Nvidia:
    name: Op-Test-Nvidia
    uses: ./.github/workflows/_runs-on-nv-step2.yml
    with:
      all_coverage: ${{ secrets.ALL_COVERAGE }}
      require_coverage: ${{ secrets.REQUIRE_COVERAGE }}
